// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig } from "prisma/config";
import { readFileSync } from "fs";

let dbUrl = process.env.DATABASE_URL;
try {
  const envLocal = readFileSync(".env.local", "utf-8");
  const dbUrlMatch = envLocal.match(/DATABASE_URL="([^"]+)"/);
  if (dbUrlMatch) {
    dbUrl = dbUrlMatch[1];
  }
} catch (e) {
  // Ignore
}


export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: dbUrl,
  },
});
